name: vpay
description: vPay Flutter application
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  uuid: ^4.2.1
  supabase_flutter: ^2.3.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5 
  flutter_riverpod: ^2.4.9
  go_router: ^15.0.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.4.0
  url_launcher: ^6.2.0
  shimmer: ^3.0.0
  flutter_chat_ui: ^2.3.1
  cupertino_icons: ^1.0.8
  upi_india: ^3.0.1
  qr_code_scanner: ^1.0.1
  local_auth: ^2.1.8
  pay: ^3.2.1
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.2.2
  latlong2: ^0.9.0
  google_maps_flutter_web: ^0.5.12
  gotrue: ^2.11.1
  win32: ^5.10.1
  vm_service: ^15.0.0
  lottie: ^3.3.1
  flutter_animate: ^4.5.0
  flex_color_scheme: ^8.2.0
  dynamic_color: ^1.6.9
  timeago: ^3.1.0
  file_picker: ^10.1.9
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/eye_password.png
    - assets/images/facebook logo.png
    - assets/images/google logo.png
    - assets/images/logo_1.png
    - assets/animations/
    - assets/animations/night_owl.json
    - assets/animations/speedster.json
    - assets/animations/helper.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
